name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: node:18
      options: --user root
    permissions:
      contents: write # Grant write permissions to the GITHUB_TOKEN

    steps:
      - name: Install build dependencies
        run: apt-get update && apt-get install -y git openssh-client

      - name: Checkout
        uses: actions/checkout@v3

      - name: Clean install dependencies
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: taiwanweather.com
