name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write permissions to the GITHUB_TOKEN

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean and install dependencies
        run: npm ci

      - name: Clean dist directory
        run: rm -rf dist

      - name: Build
        run: NODE_OPTIONS=--no-node-snapshot npm run build

      - name: List dist directory contents
        run: ls -R dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
